services:
  odoo:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    depends_on:
      - db
    ports:
      - "8069:8069"
      - "8072:8072" # Live reload port
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - .:/mnt/extra-addons/product_image_export
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
      - PYTHONUNBUFFERED=1 # Output Python logs immediately
    restart: always
    command: -- --dev=all

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
    volumes:
      - odoo-db-data:/var/lib/postgresql/data
    restart: always

volumes:
  odoo-web-data:
  odoo-db-data:
